### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Shuvam586** [SoftVibes/Softex#1]
when will Softex be launched? i need to do webDev and vs code is very slow. i wish to use Softex as my primary code editor. can you please give a date on when Softex will be launcher please.

**Comment by Shuvam586** [comment]
mr. developer, this is absolutely outrageous. i have opened this issue last week, yet there has been no response whatsoever. if this behaviour continues i will have no option but to report you to the authorities.

**Comment by SoftVibes** [comment]
> when will Softex be launched? i need to do webDev and vs code is very slow. i wish to use Softex as my primary code editor. can you please give a date on when Softex will be launcher please.

very soon hopefully, I can begin work on it after my exams get over, but I am a lazy shrimp so hopefully by the end of the year :D

**Comment by Shuvam586** [comment]
although this significantly hinders my development workflow, i am really grateful that one of my best-est friends has taken the initiative to build a text editor that one day, i will be able to brag about. hugs and cheers

**Comment by SoftVibes** [comment]
> although this significantly hinders my development workflow, i am really grateful that one of my best-est friends has taken the initiative to build a text editor that one day, i will be able to brag about. hugs and cheers

:)
